services:
  # Serviço para o PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Mapeia a porta externa 5435 para a porta interna 5432
    networks:
      - default

  # Serviço para o Apache Airflow
  airflow:
    image: apache/airflow:2.2.3
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db  # Mantém a porta interna 5432
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - TOMTOM_API_KEY=${TOMTOM_API_KEY}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: airflow standalone
    networks:
      - default

  # Serviço para o Metabase
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      - MB_JETTY_PORT=3000
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase_db
      - MB_DB_PORT=5432  # Mantém a porta interna 5432
      - MB_DB_USER=airflow
      - MB_DB_PASS=airflow
      - MB_DB_HOST=postgres
    ports:
      - "3000:3000"
    volumes:
      - ./metabase/data:/metabase-data
    depends_on:
      - postgres
    networks:
      - default

networks:
  default:
    driver: bridge
